PresentacionMVC/Controllers/EnvioController.cs
using BussinesLogic.LControllers;
using CommonSolution.DTO.Camiones;
using CommonSolution.DTO.Clientes;
using CommonSolution.DTO.Envios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentacionMVC.Controllers
{
    public class EnvioController : Controller
    {
        public ActionResult AgregarEnvio()
        {
            return View();
        }

        public ActionResult AgregarNuevoEnvio(EnvioDataHolder envioDT)
        {
            LEnvioController envioController = new LEnvioController();
            List<string> erroresList = envioController.AgregarEnvio(envioDT);

            if (erroresList.Count != 0)
            {
                foreach (string error in erroresList)
                {
                    ModelState.AddModelError("ErrorGeneral", error);
                }
            }
            else
            { 
                ModelState.Clear();
                ModelState.AddModelError("SuccessGeneral", "Envio registrado");
            }

            return View("AgregarEnvio");
        }
        public JsonResult GetPrecioTotal(EnvioDataHolder envioDT)
        {
            LEnvioController envioController = new LEnvioController();
            double precioTotal =  envioController.GetDatoPrecioTotal(envioDT);

            return Json(precioTotal, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult CargarMapaZona()
        {
            LZonaController zonaLController = new LZonaController();
            List<PuntosZona> puntosList = zonaLController.GetPuntosZona();

            return Json(puntosList, JsonRequestBehavior.AllowGet);
        }
    }
}

PresentacionMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentacionMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PresentacionMVC/Views/Envio/AgregarEnvio.cshtml
@model CommonSolution.DTO.Envios.EnvioDataHolder

@{
    ViewBag.Title = "Agregar envio";
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvMdxTAgkFIhI8MqCR8bE_CRHpNABl0L0&sensor=false"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvMdxTAgkFIhI8MqCR8bE_CRHpNABl0L0&callback=initMap&libraries=&v=weekly" async></script>
}

<h2>Agregar envio</h2>
<div>
    @Html.ActionLink("Ver listado de envios", "AgregarEnvio")
</div>

@using (Html.BeginForm("AgregarNuevoEnvio", "Envio"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.RemitenteId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RemitenteId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RemitenteId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ClienteDestinatarioId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClienteDestinatarioId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClienteDestinatarioId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PesoTotal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PesoTotal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PesoTotal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DescripcionContenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DescripcionContenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DescripcionContenido, "", new { @class = "text-danger" })
        </div>
    </div>
    <div style="margin-left: 600px; margin-top: -240px; position:absolute;">
        <div class="form-group" style="margin-left: 70px;">
            @Html.LabelFor(model => model.NombreDireccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreDireccion, new { id = "NombreDireccion" })
                <div style="margin-left:150px">
                    @Html.ValidationMessageFor(model => model.NombreDireccion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div id="dvMap" style="width: 500px; height: 500px; outline: 2px solid black;">
        </div>

        <div class="col-md-10">
            @Html.HiddenFor(model => model.Latitud, new { id = "campoLatitud" })
        </div>
        <div class="col-md-10">
            @Html.HiddenFor(model => model.Longitud, new { id = "campoLongitud" })
        </div>
        <div class="col-md-10">
            @Html.HiddenFor(model => model.DatoZona, new { id = "latitudZonaAdentro", @class = "form-control" })
            <div style="margin-left:150px">
                @Html.ValidationMessageFor(model => model.DatoZona, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <br /><br />

        <div style="margin-left: 80px;">
            <b>
                <div style="margin-left: 120px;">
                    Datos de pago
                </div>
                <br />
                Debito
                @Html.RadioButtonFor(model => model.TipoPago, "Debito")
                &nbsp Credito
                @Html.RadioButtonFor(model => model.TipoPago, "Credito")
                &nbsp Efectivo
                @Html.RadioButtonFor(model => model.TipoPago, "Efectivo")
                &nbsp Mercado pago
                @Html.RadioButtonFor(model => model.TipoPago, "Mercado pago")
            </b>
        </div>
        <br /><br /><br />

    <div class="form-group">
        @Html.LabelFor(model => model.PrecioTotal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="precioTotal" id="precioTotal" size="40" class="form-control" readonly>
        </div>
        <br /><br />
        <div style="margin-left: 290px;">
            <input type="button" onclick=CalculoPrecioTotal() id="btnCalcular" value="Calcular" class="btn btn-info" />
            <div id="errorCalculoPrecioTotal" class="text-danger" style="margin-left: -200px;"></div>
        </div>
    </div>

    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-8">
            <input type="submit" value="Pagar" class="btn btn-default"/>
        </div>
    </div>
    <div style="margin-left: 130px;">
        <strong> @Html.ValidationMessage("ErrorGeneral", new { @class = "text-danger" }) </strong>
    </div>
    <div style="margin-left: 155px;">
        <strong> @Html.ValidationMessage("SuccessGeneral", new { @class = "text-success" }) </strong>
    </div>

    <br /><br /><br />

</div>
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    @Scripts.Render("~/bundles/mapaEnvios");
    @Scripts.Render("~/bundles/precioTotal");
}

PresentacionMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>DAK</h1>
    <p class="lead">Aplicacion de registro de envios DAK</p>
</div>

PresentacionMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script> <!-- Icons -->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">

                <div class="dropdown" style="margin-top: 10px;">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        Personas
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                    </ul>
                </div>
                <div class="dropdown" style="margin-top: -34px; margin-left: 100px;">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        Zonas
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                    </ul>
                </div>
                <div class="dropdown" style="margin-top: -34px; margin-left: 180px;">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        Camiones
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                    </ul>
                </div>
                <div class="dropdown" style="margin-top: -34px; margin-left: 285px;">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        Envios
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Nuevo envio", "AgregarEnvio", "Envio")</li>
                    </ul>
                </div>
                <div class="dropdown" style="margin-top: -34px; margin-left: 370px;">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        Reportes
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                    </ul>
                </div>



                <div style="margin-top: -40px; margin-left: 900px; position: absolute;">
                    <span class="iconify" style="color: white; width: 50px; height: 45px; cursor: pointer;" data-icon="ri:logout-box-line" data-inline="false" onclick="location.href='@Url.Action("Logout", "Login")'"></span>
                </div>

                <div style="margin-top: -40px; margin-left: 820px; position: absolute;">
                    <span class="iconify" style="color: white; width: 50px; height: 45px; cursor: pointer;" data-icon="whh:house" data-inline="false" onclick="location.href='@Url.Action("Index", "Home")'"></span>
                </div>

                <div id="digital_clock" style="color:whitesmoke; float: right; margin-top: -30px;">00:00:00</div>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DAK </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Clock")
    @RenderSection("scripts", required: false)
</body>
</html>